[package]
name = "nineteen"
version = "0.1.0"
authors = ["FMarno <finlay.marno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.intcomputer]
path = "../intcomputer"